module.exports = {
  auth: require("./auth"),
  dashboard: require("./dashboard"),
  users: require("./users"),
  branches: require("./branches"),
  positions: require("./positions"),
  references: require("./references"),
  assessments: require("./assessments"),
  questionBank: require("./question-bank"),
  analytics: require("./analytics"),
  settings: require("./settings"),
  gamificationRules: require("./gamification-rules"),
  invitations: require("./invitations"),
  profile: require("./profile"),
  permissions: require("./permissions"),
  courses: require("./courses"),
  badges: require("./badges"),
  levels: require("./levels"),
  legacy: require("./legacy"),
};
