module.exports = {
  auth: require("./auth"),
  dashboard: require("./dashboard"),
  users: require("./users"),
  branches: require("./branches"),
  positions: require("./positions"),
  references: require("./references"),
  assessments: require("../assessment/admin"),
  questionBank: require("./question-bank"),
  analytics: require("../analytics/admin/routes"),
  settings: require("./settings"),
  gamificationRules: require("./gamification-rules"),
  invitations: require("../invitations/admin/routes"),
  profile: require("./profile"),
  permissions: require("./permissions"),
  courses: require("../courses/admin/routes"),
  badges: require("./badges"),
  levels: require("./levels"),
};
