module.exports = {
  auth: require("../auth/admin/routes"),
  dashboard: require("./dashboard"),
  users: require("./users"),
  branches: require("./branches"),
  positions: require("./positions"),
  references: require("./references"),
  assessments: require("../assessment/admin"),
  questionBank: require("./question-bank"),
  analytics: require("../analytics/admin/routes"),
  settings: require("./settings"),
  gamificationRules: require("../gamification/admin/rules/routes"),
  invitations: require("../invitations/admin/routes"),
  profile: require("./profile"),
  permissions: require("./permissions"),
  courses: require("../courses/admin/routes"),
  badges: require("../gamification/admin/badges/routes"),
  levels: require("../gamification/admin/levels/routes"),
};
