-- Sprint 4: обязательность подтем и подготовка к reorder API
-- Дата создания: 2026-04-22

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

DROP PROCEDURE IF EXISTS _mig017;
CREATE PROCEDURE _mig017()
BEGIN
  DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
  DECLARE CONTINUE HANDLER FOR 1061 BEGIN END;
  DECLARE CONTINUE HANDLER FOR 1091 BEGIN END;
  DECLARE CONTINUE HANDLER FOR 1146 BEGIN END;

  ALTER TABLE course_topics
    ADD COLUMN is_required TINYINT(1) NOT NULL DEFAULT 1 AFTER order_index,
    ADD INDEX idx_course_topics_required (is_required);
END;

CALL _mig017();
DROP PROCEDURE IF EXISTS _mig017;

SET FOREIGN_KEY_CHECKS = 1;
